package com.xcelenergy.registration.wsdl.serviceplan;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-16T23:46:45.221-05:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://soap.ws.registration.utility.com/", name = "UtilityService")
@XmlSeeAlso({ObjectFactory.class})
public interface UtilityService {

    @WebMethod
    @RequestWrapper(localName = "getAllServicePlans", targetNamespace = "http://soap.ws.registration.utility.com/", className = "com.xcelenergy.registration.wsdl.serviceplan.GetAllServicePlans")
    @ResponseWrapper(localName = "getAllServicePlansResponse", targetNamespace = "http://soap.ws.registration.utility.com/", className = "com.xcelenergy.registration.wsdl.serviceplan.GetAllServicePlansResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.xcelenergy.registration.wsdl.serviceplan.ServicePlan> getAllServicePlans() throws Exception_Exception;
}
