package com.xcelenergy.registration.wsdl.serviceplan;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-16T23:46:45.229-05:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "UtilityService", 
                  wsdlLocation = "file:/C:/BCJ_May_16/WebServiceSpringHibernate/XcelEnergy/src/main/resources/CustomerUtilityService.wsdl",
                  targetNamespace = "http://soap.ws.registration.utility.com/") 
public class UtilityService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.ws.registration.utility.com/", "UtilityService");
    public final static QName UtilityServiceImplPort = new QName("http://soap.ws.registration.utility.com/", "UtilityServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/BCJ_May_16/WebServiceSpringHibernate/XcelEnergy/src/main/resources/CustomerUtilityService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UtilityService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/BCJ_May_16/WebServiceSpringHibernate/XcelEnergy/src/main/resources/CustomerUtilityService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UtilityService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UtilityService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UtilityService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UtilityService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UtilityService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UtilityService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UtilityService
     */
    @WebEndpoint(name = "UtilityServiceImplPort")
    public UtilityService getUtilityServiceImplPort() {
        return super.getPort(UtilityServiceImplPort, UtilityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UtilityService
     */
    @WebEndpoint(name = "UtilityServiceImplPort")
    public UtilityService getUtilityServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UtilityServiceImplPort, UtilityService.class, features);
    }

}
