
package com.xcelenergy.registration.wsdl.serviceplan;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-16T23:46:45.125-05:00
 * Generated source version: 3.1.7
 * 
 */
public final class UtilityService_UtilityServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.ws.registration.utility.com/", "UtilityService");

    private UtilityService_UtilityServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UtilityService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UtilityService_Service ss = new UtilityService_Service(wsdlURL, SERVICE_NAME);
        UtilityService port = ss.getUtilityServiceImplPort();  
        
        {
        System.out.println("Invoking getAllServicePlans...");
        try {
            java.util.List<com.xcelenergy.registration.wsdl.serviceplan.ServicePlan> _getAllServicePlans__return = port.getAllServicePlans();
            System.out.println("getAllServicePlans.result=" + _getAllServicePlans__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
